#!/bin/bash
# 1st argument is xcentral, 2nd is ycentral, 3rd is zcentral, 4th is the name of the file without .nii.gz, 5th is R (right) or L (left)
export PATH="/Applications/ITK-SNAP.app/Contents/bin/":$PATH
printf "\nThe processing of $4.nii.gz has been started\n"

a=$(($1-12))
b=$(($2-12))
c=$(($3-12))

c3d $4.nii.gz -region "$a"x"$b"x"$c"vox 22x22x22vox -o $4_$5.nii.gz

Ni=22
#Ni=$(echo `c3d $4_$5.nii.gz -info` | cut -f5 -d' ' | egrep -o [0-9]+)

for (( i=0; i<$Ni; i++ ))
do
	for (( j=0; j<$Ni; j++ ))
	do
		for (( k=0; k<$Ni; k++ ))
		do
			echo `c3d $4_$5.nii.gz -probe "$i"x"$j"x"$k"vox` | cut -f9 -d' ' >> $4_$5.txt
		done
	done
done

printf "\nThe processing of $4.nii.gz has been finished\n\007"
